### ISSUE TITLE
Allow installation into other directories

### ISSUE THREAD

**Issue by Ndolam** [Thorn-Inurcide/tde-slackbuilds#12]
These SlackBuilds currently clobber a kde4 installation, as suggested by the README.
While it may be the case that not a lot of people want to use both, I see some value into being able to install TDE into another place in the filesystem, so that the two can coexist peacefully.  As a start towards that end, I modified a handful of lines in tqt3.SlackBuild so that you can set a variable specifying the "root" of the installation directory and it installs everything (except the profile.d scripts) into that directory.

For example, setting that variable to /opt2 installs tqt3 into /opt2/usr/doc/ and /opt2/usr/lib64/.  (In fact, I also modified build-deps.sh to set this variable, but that's a trivial change.)  I haven't carried on from there, so I am uncertain of the level of effort or the chance of success.  Is there anyone involved with or watching Thorn-Inurcide/tde-slackbuilds who is interested in carrying on with this idea?  I have attached the modified SlackBuild (with a .txt extension to make github happy) to this message.

[tqt3.SlackBuild.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/254980/tqt3.SlackBuild.txt)

**Comment by Thorn-Inurcide** [comment]
Hi
Originally I wanted to try tde and couldn't find scripts anywhere so I had
to make them so I was the only person at first using these and I didn't
even take KDE into consideration because I don't like it. I think upstream
even recommends installing to /opt I just didn't care because it didn't
interfere with anything of mine.  Lately you and another person have been
helping me and if you really feel like it's worth it I have no problems
adjusting the installation directory when I have more time.  Originally
though I was the only person using these and that's why they are set up for
/usr . I'm not sure who all is using them now.

**Comment by Ndolam** [comment]
I'm not a kde fan either, but still, I see value in allowing the two to co-exist.

I found your scripts "by accident".  I suspect a lot of people would be interested in using them if they knew about them.  Are you interested in letting the tde people advertise their existence?  You (or I'll do it, if you like) could email kb9vqf@pearsoncomputing.net and ask him to put a link to your github at https://www.trinitydesktop.org/ in the "Getting TDE section".

Cheers.

**Comment by Thorn-Inurcide** [comment]
Lets get tde adjusted to install to /opt first and then do that.  If you
want you can start changing some of the scripts to install to /opt I think
it would be good to figure out how to submit the changes through github to
so I can just merge them for you.  And if you're willing to do that I cam
give you push access and you can make the changes yourself.  I gave another
guy push access and he filled up the apps directory. So I have no problem
doing that if you learn git hub a little more and want to help

**Comment by Thorn-Inurcide** [comment]
Another thing that could be done.  Is start a new tde repo for the bulls
independent of my account just for tde as well

**Comment by Thorn-Inurcide** [comment]
Builds""""

**Comment by ryanpcmcquen** [comment]
I am in favor of `/opt/`.

**Comment by Thorn-Inurcide** [comment]
Ok.  /opt it is.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
I just checked out the tqt3.SlackBuild you submitted to me, looks good. 
Question I have is instead of an install_root variable, how about we just force installation to
/opt/trinity    https://wiki.trinitydesktop.org/How_to_Build_TDE_Core_Modules
The variable is good because we can pass whatever directory the user wants via the build-deps, build-core scripts, but if the user wants to build each script individually would have to manually specify that for each script, and there are quite a bit of them.

**Comment by Thorn-Inurcide** [comment]
@Ray-V  @ryanpcmcquen 
What you think about this?

**Comment by Ndolam** [comment]
I'm fine with installation in /opt/trinity.
(Having said that, a user building individual packages could do something like
export INSTALL_ROOT=/opt42/TrInItY/
and then happily build away.  But if no-one has any interest in allowing this to be easily specified, then I'm happy to do without it.  Especially if more people are enthusiastic that way.)

Attached to this message is a version (untested, but trivially modified from my previous version) of tqt3.SlackBuild which installs into /opt/trinity.  It doesn't exactly follow https://wiki.trinitydesktop.org/How_to_Build_TDE_Core_Modules, but the last time I tried following those directions things failed for me when building (IIRC) tdebindings.  I didn't have time then to track down exactly where things went off the rails, but it is possible the attached SlackBuild is somehow complicit in the problems.

Speaking of inability to follow directions, the last time I tried to collaborate via github with someone, I followed the "directions for n00bs" at https://guides.github.com/activities/hello-world/, but that was, apparently, too advanced for me.  I'd be happy to contribute to this effort The Right Way, but before I can do that I will, apparently, need to find the "github for complete, utter, and total morons" guide. :-(

Cheers.

[tqt3.SlackBuild-opt-trinity.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/255611/tqt3.SlackBuild-opt-trinity.txt)

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
I'll check that out in a bit. I guess if we get no other input on it in the next day or so, we can make the decision ourselves, especially since I don't know how long I'll have this computer up and running before I need to pack it back up

**Comment by Ndolam** [comment]
Sure thing.  I'm happy with the /opt/trinity suggestion, if we can get everything to build happily there.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
I'll run it through /opt/trinity
Only thing I see needs adjusted is the tqt3 to qt3 symlink, should be left in /usr/include. 
I don't remember what it was now but something was absolutely refusing to build without it.
I'm sure I can direct whatever it was to the tqt3 includes, but the problem is I don't remember what it is. So for now we will keep that symlink and when I have time, I'll gladly go through and find it again

**Comment by ryanpcmcquen** [comment]
I like the variable philosophically, but I would be fine with it being a hard-coded directory.

**Comment by Thorn-Inurcide** [comment]
We can roll with the install_root variable if that's what people like.

**Comment by ryanpcmcquen** [comment]
My vote is for whatever is easiest to maintain. 😺

**Comment by Thorn-Inurcide** [comment]
I think I just got around that symlink, and have them compiling from /opt/trinity

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
you said you already have a modified build-deps.sh for the INSTALL_ROOT variable,
may I have it please?

**Comment by Thorn-Inurcide** [comment]
Configuring tqca-tls ...
Verifying TQt 3.x Multithreaded (MT) build environment ... fail

There was an error compiling 'conf'.  Be sure you have a proper
TQt 3.x Multithreaded (MT) build environment set up.

this error is driving me insane

**Comment by Ray-V** [comment]
@Thorn-Inurcide
Just caught up with this conversation, so this is just my immediate 2 cents worth ..

My view is it's your project, so you do what you want. Depends on whether you want it to remain 'personal' which I'm happy with.

But why hurry about making a final decision. What is there at the moment works, so let's try things out and sort out the pitfalls and when you're back in business, decide then.

Also, we may be trying to re-invent the wheel here. The SlackBuild scripts for KDE3 64-bit install to /opt/kde3 [with Qt in /opt/kde3/lib64/qt3/] so we may be able to find some guidance there.


@Ndolam
Have you set up a fork of the project? It's a lot easier to make changes to a fork [where you can try things out, and make mistakes without affecting the main project] and then do a pull request - it seems to be working OK for me so far.

**Comment by Ndolam** [comment]
Thorn-Inurcide: attached.
[build-deps.sh.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/257243/build-deps.sh.txt)

**Comment by Ndolam** [comment]
Ray-V: I have not (yet) set up a fork, although the thought crossed my mind.
As you may have seen, I'm github-challenged, but let me ask the assembled experts here another question: would it be possible *and make sense* for Thorn to create a branch, give write perms on the branch to those of us who would like to contribute, and keep (as you correctly observe) the main project in a pristine working state until the "install somewhere else" branch is working?
The thing I like about this is that it might make it a bit easier for other Slackware people to figure out what it going on (and maybe contribute) when they are looking on github.  Otherwise they may waste their time trying to figure out which of the many forks / branches / versions is the one they really want.
(If, however, what I just said is nonsense in the github world, feel free to straighten me out.  Be gentle.  :-)

**Comment by Thorn-Inurcide** [comment]
Think I found my problem. In the profile.d folder, the environment scripts, how am I going to pass the $INSTALL_ROOT variable to those so they look in the correct directory? Have to sed that in the SlackBuild too? Man I should stop be lazy and learn more shell scripting.
Can probably add $INSTALL_ROOT variable into the *.csh and .*sh scripts in profile.d but I'm sure that would need to be changed to a hard coded value during the installation process. It would just be an unbound variable if not.

**Comment by ryanpcmcquen** [comment]
Check out around line 67:

https://slackbuilds.org/cgit/slackbuilds/tree/multimedia/spotify/spotify.SlackBuild

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen 
sweet ill look into that tomorrow, I just got that package tqca-tls to compile, I had to patch the configure script
Though I'll need it to be changed in the SB to accept the INSTALL_ROOT variable of that's the route taken

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen 
the include directory in the configure script is hard coded to /usr/include/tqt even if the qtdir is specified and changed, so stupid

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
I could indeed create a development branch, and might anyways after stable is out and current is moving along again in the future. I don't really see much need for it at the moment though. I'd rather have the help directly to the master branch.  Maybe try Ray-V idea of forking it and making changes there then submitting them to me?

I have the deps folder all compiled in /opt/trinity, but tdelibs is failing, so i'll look at that later next. I had a long day and going to call it a night

**Comment by ryanpcmcquen** [comment]
You can do replacement with variables using `sed`:

```
sed -i.bak 's@/usr/include/tqt@${INSTALL_ROOT}@g' *
```

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen 
That's awesome, I just bookmarked a page on learning sed last night, but this is the first I've been at the pc today

**Comment by ryanpcmcquen** [comment]
This one helped me:
http://www.grymoire.com/Unix/Sed.html

:smiley:

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen  thats what I have lol
I un patched that configure script. turns out tqtinterface still needs to install to /usr regardless of where the rest is installed too

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen 
Not that any of it has mattered because tdelibs still fails to build

**Comment by Thorn-Inurcide** [comment]
[Deps.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/258480/Deps.tar.gz)
@Ndolam 
@ryanpcmcquen 
@Ray-V 

Anyone want to see what is going wrong?

**Comment by Ndolam** [comment]
Not immediately, but do the "ton of links" and the pkgconfig stuff really want to go in /usr/lib rather than /opt/trinity/usr/lib ?  (I'm talking about tqt3.SlackBuild here.)

**Comment by Ndolam** [comment]
Also more a question than a wild guess, in dbus-tqt.SlackBuild, does CMAKE_INSTALL_PREFIX want to be /opt/trinity/usr rather than just /opt/trinity?
Same question for dbus-1-tqt.SlackBuild.
And the analogous question for QT_PREFIX_DIR in tqtinterface.SlackBuild.

**Comment by Ray-V** [comment]
<pre>
If the error message with tdelibs build is the one I got about connectionsettings.cpp, 
then that is because the TQt libraries can't be found.

Build based on Deps.tar.gz posted above, except with tqtinterface installed to /opt/trinity.

Need to go back to tqt3.SlackBuild and add TQt library directories to /etc/ld.so.conf and update PKG_CONFIG_PATH:

NOTE: I'm using /opt/trinity/lib${LIBDIRSUFFIX} NOT /opt/trinity/usr/lib${LIBDIRSUFFIX} [and with tqca-tls]
------------------------------------------
# Add this to the doinst.sh:
mkdir -p $PKG/install
cat <<EOINS >> $PKG/install/doinst.sh
# Add TQt library directories to /etc/ld.so.conf:
if ! grep /opt/trinity/lib${LIBDIRSUFFIX} etc/ld.so.conf 1> /dev/null 2> /dev/null ; then
  echo "/opt/trinity/lib${LIBDIRSUFFIX}" >> etc/ld.so.conf
fi
if ! grep /opt/trinity/lib${LIBDIRSUFFIX}/tqt3-R14.0.3/lib etc/ld.so.conf 1> /dev/null 2> /dev/null ; then
  echo "/opt/trinity/lib${LIBDIRSUFFIX}/tqt3-R14.0.3/lib" >> etc/ld.so.conf
fi
if [ -x /sbin/ldconfig ]; then
  /sbin/ldconfig 2> /dev/null
fi

# Update PKG_CONFIG_PATH:
echo "#!/bin/sh
PKG_CONFIG_PATH=\${PKG_CONFIG_PATH}:/opt/trinity/lib${LIBDIRSUFFIX}/pkgconfig
export PKG_CONFIG_PATH
" > /etc/profile.d/pkgconfig-tqt.sh

echo "#!/bin/csh
setenv PKG_CONFIG_PATH \${PKG_CONFIG_PATH}:/opt/trinity/lib${LIBDIRSUFFIX}/pkgconfig
" > /etc/profile.d/pkgconfig-tqt.csh

chmod 755 /etc/profile.d/pkgconfig-tqt*
[[ $(which bash) ]] && /etc/profile.d/pkgconfig-tqt.sh
[[ $(which csh) ]] && /etc/profile.d/pkgconfig-tqt.csh


# Update the desktop database:
....
------------------------------------------

Then opened up a new terminal and tdelibs built OK.

Note:
# Update PKG_CONFIG_PATH:
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/trinity/lib${LIBDIRSUFFIX}/pkgconfig
 didn't work, so I used the above method which needs working on but does the job for now.

Note-2:
I guessed the old KDE3 SlackBuilds would be useful ..
</pre>
Sorry about the formatting, but copy and paste to a text editor will work.

**Comment by Ray-V** [comment]
Forgot that I'd also patched configure in tqca-tls.SlackBuild:
\# This configure script doesn't accept crap for arguments see ./configure --help to verify
sed -i "s|/usr/include/tqt|/opt/trinity/include/tqt|g" configure
LDFLAGS="$SLKLDFLAGS" \

**Comment by Ray-V** [comment]
These scripts build a basic working TDE in /opt/trinity.

It's a work-in-progress - I'm trying to install tqtinterface to /opt/trinity but can't get tdemultimedia to build then; and updating environment variables during the build.

I don't use tdm, so that's untested.

tdebase.SlackBuild includes a line - 'ln -sf xinitrc.tde xinitrc'

tdegraphics.SlackBuild has KUICKSHOW="ON". In view of the note in the script, you may want to put this to OFF.


[Deps-Core-opt.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/264666/Deps-Core-opt.tar.gz)

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Awesome , I just downloaded your tarball but won't be able to look at it just yet. I actually just sat down to catch up reading what I missed last couple of days on here when you posted it

**Comment by Thorn-Inurcide** [comment]
@Ndolam I overlooked that, those links should be in /opt/trinity/usr/lib as you mentioned

**Comment by Ray-V** [comment]
These scripts build a basic working TDE in {INSTALL_ROOT} as per Ndolam's idea.

Added a script [set-env.sh] to set up environment variables needed for the build, called that from build-deps.sh and build-core.sh, and replaced /opt/trinity in the SlackBuilds with ${INSTALL_ROOT}.

Still don't know why tdelibs.SlackBuild and tdemultimedia.SlackBuild can't find the tqt3 headers, so added SLKCFLAGS variable to set-env.sh and also to the tdelibs and tdemultimedia SlackBuilds for x86_64. I'm only building for 64bit so don't know whether it's needed for i586, etc.

[Note: shouldn't all i486 references in the SlackBuilds now be i586?]
[Deps-Core-INSTALL_ROOT.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/265191/Deps-Core-INSTALL_ROOT.tar.gz)

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
[Note: shouldn't all i486 references in the SlackBuilds now be i586?]
Seems like it should I know they use i586 now. 
Downloading your tarball now. will run that this evening sometime.

**Comment by Thorn-Inurcide** [comment]
@Ray-V  looks great.
I'll get the rest of the build scripts in core updated as soon as i can and start on apps too. And we can make one giant update(or you can) i know you've done a lot already though. If you do go ahead and bring everything else up to build with install_root, feel free to make the merger yourself. Don't forget to credit yourself too.

**Comment by Thorn-Inurcide** [comment]
On another note, I will probably be packing my PC back up soon too =[
I'll be leaving here on the first and want to be ready to go. Just so you guys know I'll be away for a while =[

**Comment by Ray-V** [comment]
Have tidied up set-env.sh

Updated tdelibs and tdemultimedia SlackBuilds - finding ntqglobal.h etc. was a 'C' requirement not 'C++'.
I've set up a TQT_INCLUDE_PATH, and added it into the CFLAGS option in the SlackBuilds.


For tqt3.SlackBuild:

Updated doinst.sh:
checked for existing paths, and appended TDE pkgconfig path to existing /etc/profile.d/pkgconfig.[c]sh scripts instead of creating new scripts

Updated tqt.[c]sh:
added ${INSTALL_ROOT}/bin to PATH
 \- done a check for existing in tqt.sh, but not in tqt.csh as I don't know csh syntax.

--------------------------------------------
What do you think about adding a 'src' directory for copies of source archives, it will mean just setting a link in the SlackBuilds:

\# Where do we look for sources?
SRCDIR=$(cd $(dirname $0); pwd)
ln -sf $SRCDIR/../../src/${PRGNAM}-${VERSION}.tar.bz2 $SRCDIR

At the moment, all source archives have to be copied to individual package directories.
Similarly, anybody using a 'machine.conf' [whatever that is] would only have to install one copy.

.. and adding a TDE_MIRROR option in set-env.sh?

.. and setting a NUMJOBS option ..?

I've set these up in the attached tarball.

@Thorn-Inurcide
Are you thinking of adding a build-apps.sh to the project?

[Deps-Core-INSTALL_ROOT-2.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/274372/Deps-Core-INSTALL_ROOT-2.tar.gz)

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
adding build-apps should probably be added. Not entirely sure why I never did that.
That all looks and sounds great. Sorry been slow responses. Making lots of decisions in life right now.
I'll be taking my PC down in the next day or two as well.  

Similarly, anybody using a 'machine.conf' [whatever that is] would only have to install one copy.
not sure what that is either I guess I could log into steam and see if alienbob is online and ask 

If you convert everything over feel free to push it. And Thanks, I know I couldn't have done this myself, even if I had time too. If you don't want to push that's fine. I'll eventually be able to sit down and relax in front of the PC and do it. I have had some free time but so much on my mind just haven't had the motivation.

**Comment by Ray-V** [comment]
Making progress.
\---------------------
New scripts:

build-libs.sh
build-apps.sh
get-source.sh - Have extracted a block of common code in each SlackBuild to this separate script for ease of maintenance and to make the SlackBuilds easier to read. The 'machine.conf' code needs adapting.
\---------------------
set-env.sh:

Added some more options

I'm running the whole build in ram, and the build slowed to a crawl by the time it got to tdevelop, so I added a KEEP_BUILD option.
\---------------------
Updated tde.{,c}sh to include TDE man pages in MANPATH
\---------------------
Changed tdewebdev, amarok and dolphin to build with automake/configure. The dolphin cmake build is incomplete, and I don't know enough about CMakeLists.txt files to edit them.

Building tdenetwork using cmake segfaults and I haven't been able to find out yet what the problem is, so the included build uses automake/configure.
\---------------------
Changed INSTALL_ROOT to INSTALL_TDE as an INSTALL_ROOT variable is used in the tqt3 build.
\---------------------
All build OK on 64bit.


@Thorn-Inurcide

I haven't merged/pushed these because

1] There are a lot of changes and I think you should be OK with them first - no hurry, please don't feel rushed on my account.

2] I don't use kdm, so I think that should be tested.

3] I've only built this on x86_64

4] You mentioned for the gwenview-i18n Spanish translation I did that you might be able to get it checked - can you do likewise for the es.po I've included with knights? It doesn't need kbabel to edit, a text editor will do. The SlackBuild will build without it so it could be left out for now.

[full-build-1.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/292093/full-build-1.tar.gz)

**Comment by Thorn-Inurcide** [comment]
Yeah I'm leaving here Friday so I'm packing up and thanks again.  Once I'm
set up I'll sit down with all of this. Not exactly sure how long that will
be.
On May 31, 2016 3:40 PM, "Ray-V" <notifications@github.com> wrote:

Making progress.
---------------------
New scripts:

build-libs.sh
build-apps.sh
get-source.sh - Have extracted a block of common code in each SlackBuild to
this separate script for ease of maintenance and to make the SlackBuilds
easier to read. The 'machine.conf' code needs adapting.
---------------------
set-env.sh:

Added some more options

I'm running the whole build in ram, and the build slowed to a crawl by the
time it got to tdevelop, so I added a KEEP_BUILD option.
---------------------
Updated tde.{,c}sh to include TDE man pages in MANPATH
---------------------
Changed tdewebdev, amarok and dolphin to build with automake/configure. The
dolphin cmake build is incomplete, and I don't know enough about
CMakeLists.txt files to edit them.

Building tdenetwork using cmake segfaults and I haven't been able to find
out yet what the problem is, so the included build uses automake/configure.
---------------------
Changed INSTALL_ROOT to INSTALL_TDE as an INSTALL_ROOT variable is used in
the tqt3 build.
---------------------
All build OK on 64bit.

@Thorn-Inurcide <https://github.com/Thorn-Inurcide>

I haven't merged/pushed these because

1] There are a lot of changes and I think you should be OK with them first
- no hurry, please don't feel rushed on my account.

2] I don't use kdm, so I think that should be tested.

3] I've only built this on x86_64

4] You mentioned for the gwenview-i18n Spanish translation I did that you
might be able to get it checked - can you do likewise for the es.po I've
included with knights? It doesn't need kbabel to edit, a text editor will
do. The SlackBuild will build without it so it could be left out for now.

full-build-1.tar.gz
<https://github.com/Thorn-Inurcide/tde-slackbuilds/files/292093/full-build-1.tar.gz>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Thorn-Inurcide/tde-slackbuilds/issues/12#issuecomment-222813358>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJ54nCKCE6PjjsAN73WrmCacmgFpyAroks5qHJzHgaJpZM4IaHhP>
.

**Comment by Ray-V** [comment]
More SBs and some mods
\-----------------------
Have included tidy-html5 which Quanta plus can use.

build-{deps,apps}.sh updated to include new SBs
\-----------------------
Included only updated files for existing SBs

Updated tde.{,c}sh to remove MANPATH
Updated tqt3.{,c}sh to remove PATH
PATHs now added to /etc/profile using tdebase doinst.sh [*]

tqt3 and tdebase SBs updated in line with PATHs changes

[*] Check out the last five lines of doinst.sh. I don't use .bashrc, but the as-built TDE does, and this edit may not be universally acceptable.
\-----------------------
Resolved the tdenetwork cmake segfault issue and probably safe to say it won't affect most [any other?] users.

I have qt3/kde3 installed and the kopete build in tdenetwork was finding that. Removed them and tdenetwork with cmake built OK.
\-----------------------
Only built on 64bit.


[full-build-update-1.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/300284/full-build-update-1.tar.gz)

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Cool I might have this weekend off, not sure yet, if I do I'll sit down with this
I don't normally use a .bashrc either and if I do I just have it source /etc/profile

**Comment by Thorn-Inurcide** [comment]
wow I am so behind on this.

**Comment by Ray-V** [comment]
Set up a 'dialog' based script, BUILD-TDE.sh, to front the other build scripts, and to keep that simple, moved non-TDE apps to Misc directory.

Added potracegui which prompted adding Inkscape as well.

Included hack for tdebase [see README] for tree-view in konqueror file-manager.

Repackaged all the build scripts:

[full-build-2.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/368130/full-build-2.tar.gz)

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Amazing, Thank you. I'm getting ready to wind down for the night, I will look at this after work tomorrow. Sorry I'm slacking on this I'll get my ass in gear this week.

**Comment by Thorn-Inurcide** [comment]
@Ray-V Are you still on -current? Or 14.2?

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I'm running your script right now, and I have a 3 day weekend
doing the downloads individually. Then will do it again when them all downloaded at once.
Everything looks great to me though. Basically I'm just making sure all the download links are working before merger. Which you're more than welcome to do, or I will.

**Comment by Thorn-Inurcide** [comment]
ahh shit I need to hook the 32 bit machine back up too and check that don't i lol

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen 
Do you still have a 32 bit machine running?

**Comment by ryanpcmcquen** [comment]
Unfortunately, no.

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
for tdegraphics
DBUILD_KUICKSHOW="ON" \

needs to be OFF because of not having imlib, I've been unable to get it to build on 14.2 or -current for awhile too, do you have it built?

**Comment by Thorn-Inurcide** [comment]
@ryanpcmcquen 
okay thanks man, I'll hook up mine this weekend

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
Want to try the provided tarball? from Ray-V?
full-build-2.tar.gz
It's up about 9 comments from this one

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
it would appear they have imlib patched and building at sbo, think it's worth adding? or just making mention of that for someone who might be interested in it?

**Comment by Ray-V** [comment]
@Thorn-Inurcide

<i>Are you still on -current? Or 14.2?</i>
A] 64-current - but they're pretty much the same thing at the moment aren't they?
   \- except for the kernel - I build my own because I need aufs, so I'm using 4.6.x, but I don't think that would impact the TDE build.

\-----------------
<i>for tdegraphics
DBUILD_KUICKSHOW="ON" \
needs to be OFF because of not having imlib, I've been unable to get it to build on 14.2 or -current for awhile too, do you have it built?</i>
A] No - cheated on this and used the 13.37 package.

\----------------
<i>it would appear they have imlib patched and building at sbo, think it's worth adding? or just making mention of that for someone who might be interested in it?</i>
A] I've just tried the SBo build and got:
load.c: In function ‘_LoadGIF’:
load.c:457:9: error: too many arguments to function 

We could add a check in the SB for whether imlib is installed:

[tdegraphics.SlackBuild-kuickshow.diff.txt](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/378351/tdegraphics.SlackBuild-kuickshow.diff.txt)

**Comment by Thorn-Inurcide** [comment]
@Ray-V  Yeah current is about the same right now
adding the check works for me. Will hook my 32 bit machine up today or tomorrow and run all these on it
everything is great on 64bit though

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
the 32 bit machine will be an all day project, its got like 1 gb of ram and an amd dual core processor

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
turns out my old pc is not 32 bit, it's 64
So i guess  I will test in Virtualbox, I use to have a 32bit laptop but i got mad at it and destroyed it last year...

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I have it running on 32 bit in a VM, but I don't have actual hardware to test on like I thought I did.
Want to consider this ready for merger?
![virtualbox_slackware_25_07_2016_13_33_16](https://cloud.githubusercontent.com/assets/10385564/17110819/cb7cae30-526c-11e6-80dc-6bc065165c0e.png)

**Comment by Ray-V** [comment]
Looks good to me. Anybody can always open an issue if any problems turn up.

Updated tdebase README:
[tdebase-README.tar.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/385792/tdebase-README.tar.gz)

**Comment by Thorn-Inurcide** [comment]
Right right, I might be home early enough tonight to do it if not I'll
merge Saturday unless you want to do it. I know I'm working a long one
tomorrow

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
@ryanpcmcquen 
@Ndolam 

Merged and closing

@Ray-V  Thanks for everything. I really appreciate this. It's amazing.

**Comment by Ndolam** [comment]
Guys, I've been out of this loop for a bit, and I am just starting a compile.
I see (in the Thorn-Inurcide/tde-slackbuilds version of tdegraphics.SlackBuild) the claim
that imlib won't build on Slackware 14.2.
It build fine for me, at least on Slackware64 14.2.

**Comment by Ndolam** [comment]
Here is my first question/comment/bug report/...
In get-source.sh there is a line
   wget ... || true
followed by a line
  if [ $? -ne 0 ...]
and $? will never be anything but 0.

(As you might guess, I found this because my attempts to d/l the source code while building failed.)

Cheers.

**Comment by ryanpcmcquen** [comment]
If `true` is removed, it will work.

**Comment by Ndolam** [comment]
And the reason that my attempts fails is because if the directory "src" does not exist at the top level when you run BUILD-TDE.sh, it doesn't get created, and then all sorts of Bad Things happen.

Might I suggest that BUILD_TDE.sh create that dir if it doesn't exist?
(Incidentally, this is a diff between Ray-V's tar file and the zip file d/l'ed from here: in Ray-V's zip there is an empty directory called "src".)

**Comment by ryanpcmcquen** [comment]
I've opened an issue and pull request for the `wget` issue.

https://github.com/Thorn-Inurcide/tde-slackbuilds/issues/14

https://github.com/Thorn-Inurcide/tde-slackbuilds/pull/13

**Comment by Thorn-Inurcide** [comment]
That was my goof, after I eat and clean up I'll sit down to this. Thank you

**Comment by Ndolam** [comment]
Thorn, thanks.

For what they are worth, here are my other thoughts and observations from compiling and installing everything:
(1) Most everything went very smoothly.  Kudos to all involved.
(2) I had speex installed already from the slackware package, but it replaced that.
     Perhaps I clicked something I shouldn't have, but it makes me wonder whether it
     (a) needs its own version, or
     (b) if not, should it check for the package before compiing a new one.
(3) The mostly-separation of KDE4 and TDE is nice.  But the TDE install scripts remove
     at least (I didn't compile everything) the following slackware packages, which have 
     no overlap:
     - libkipi
     - gwenview
     - amarok
     - k3b
     - libkexiv2
     - libdcraw
     (I would hope a TDE program uses the TDE libs when there is a Slackware lib by the
     same name, and that a Slackware program ignores /opt/trinity entirely, but I'm not sure
     that's the case.  Anyone?)
(4) The libart_gpl which BUILD-TDE.sh creates installs into /usr instead of /opt (at least for
      me today).  Is there any need for this, or is it an oversight?
(5) Same comment for mp4v2.

When I say "everything", I see that there aren't builds for everything.  For example, I see there is no libcaldav.  (One of my interests with TDE is korganizer, and having caldav support would be nice.)  Can anyone tell me whether the things that are missing are missing because
(1) no one has tried, or
(2) people have tried and had problems?

Thanks everyone.

**Comment by Thorn-Inurcide** [comment]
@Ndolam 
(2) I had speex installed already from the slackware package, but it replaced that.
Perhaps I clicked something I shouldn't have, but it makes me wonder whether it

Slackware ships speexdsp, speex shouldn't overwrite it, let me look into this, im running behind right now.

(4) The libart_gpl which BUILD-TDE.sh creates installs into /usr instead of /opt (at least for
me today). Is there any need for this, or is it an oversight?
Its system wide so is mp4v2, things outside of tde build against them. I compile either ffmpeg or vlc against it, dont remember which one off top of my head. well im not really sure if anything is using libart_gpl anymore but Slackware still ships it

When I say "everything", I see that there aren't builds for everything. For example, I see there is no libcaldav

I haven't even tried it. I can do this this weekend, unless you want to try and do it =]

Also i am aware there aren't builds for everything I have been slacking =[ been so busy I haven't even really been at my pc lately.

(3) The mostly-separation of KDE4 and TDE is nice. But the TDE install scripts remove
at least (I didn't compile everything) the following slackware packages, which have
no overlap:
- libkipi
- gwenview
- amarok
- k3b
- libkexiv2
- libdcraw
(I would hope a TDE program uses the TDE libs when there is a Slackware lib by the
same name, and that a Slackware program ignores /opt/trinity entirely, but I'm not sure
that's the case. Anyone?)

I'm guessing easiest way to go about this will be for me to just rename the tde packages for the ones that overwrite a Slackware package. like tde_amarok or something. Might not be the best naming convention just using as an example.

**Comment by Ndolam** [comment]
My bad.  I had an SBo speex installed.  Still, if there is already a "speex", it shouldn't be replaced (IMHO) unless there is a real need to do so.

Thanks for the explanation of libart and mp4v2's installation directories.

Should I open a new issue with my above (remaining) comments?  I noticed too late that this one is closed.

caldav: If I get a chance to do it this week, I'll update right away.  So if no update from me and you want to try it, by all means...

I think naming the packages with "tde" is a very good idea; this is in line with the goal of having these TDE slackbuilds do the minimum intrusive things to a "stock" Slackware system.

**Comment by Thorn-Inurcide** [comment]
Yes I think a new issue would be good
I could reopen this but the thread is pretty long might as well start a new
one.
We can have it check for speex, might as well have it check for
graphicsmagick, lxml and mp4v2 also
Which I think SBo has as libmp4v2

And thank you again

Oh about tdegraphics, did it build against imlib for you? I can remove that
comment if it did. The build auto detects if it is on the system or not

**Comment by Ndolam** [comment]
I opened two issues, as you have probably seen by now.

You are right, SBo has libmp4v2-2.0.0.  Which has one file of possible significance that mp4v2 does not have.

tdegraphics did, in fact, build after I installed imlib-1.9.15.  I just skimmed the build log, and there were lots of bitter complaints about deprecated conversions between constant strings and char-*s, but I didn't see anything else in the midst of all that noise.  And, in any case, the package build with over 1100 files in it.  For what that's worth.
